gems:
- jekyll-sitemap   # Create a sitemap using the official Jekyll sitemap gem
- jekyll-feed   # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
permalink: /:title/
name: Michael Legere
sass:
  style: :expanded # You might prefer to minify using :compressed

url:
baseurl: /TheBlog
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'
version: v1.2.0
avatar: https://mlegere1323.github.io/TheBlog/images/my_face.png
google_analytics:
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- CNAME
disqus:
footer-links:
  dribbble:
  email: m.legere1323@gmail.com
  facebook:
  flickr:
  github: mlegere1323
  instagram:
  linkedin: michael-legere-6943aa45
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter: 
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/


description: A platform for my views, knowledge, and accomplishments in programming, and life!
